[build]
base = "skym-web/" # Specify the base directory for the Next.js app
command = "bun run build"
publish = "skym-web/.next" # Path to the .next folder relative to the base directory

[[plugins]]
package = "@netlify/plugin-nextjs"
